export enum SCREENS {
  HOME_STACK = 'Cobradora',
  ORDER_STACK = 'Ordenes',
  HOME = 'Tomadora de pedidos',
  MENU = 'Menú de productos',
  PAYMENT = 'Método de pago',
  EDIT_SHOPPING_CART = 'Editar carrito de compras',
  FINISH_ORDER = 'Finalizar orden',
  ORDER_LIST = 'Lista de ordenes',
  FEL = 'FEL',
  MAINTENANCE = 'Mantenimiento',
  BACKUP = 'Backup',
  DAILY_REPORT = 'Reporte diario',
  DAILY_REPORT_STACK = 'Reportes diarios',
  EDIT_LIST_PRODUCT_STACK = 'Editar Lista de productos',
  EDIT_LIST_PRODUCT = 'Lista de productos',
  EDIT_PRODUCT = 'Editar producto',
  ADD_PRODUCT = 'Agregar producto',
  // Gastos
  GASTOS_STACK = 'Gastos',
  GASTOS = 'Registro de Gastos',
  EXPENSE_TYPE_MAINTENANCE = 'Tipos de Gasto',
}
