export enum SCREENS {
    HOME_STACK = 'Cobradora',
    ORDER_STACK = 'Ordenes',
    HOME = 'Tomadora de pedidos',
    MENU = 'Menú de productos',
    PAYMENT = 'Método de pago',
    EDIT_SHOPPING_CART = 'Editar carrito de compras',
    FINISH_ORDER = 'Finalizar orden',
    ORDER_LIST = 'Lista de ordenes',
    FEL = 'FEL',
    MAINTENANCE = 'Mantenimiento',
    MAINTENANCE_STACK='Mantenimientos',
    DAILY_REPORT = 'Reporte diario',
    DAILY_REPORT_STACK = 'Reportes diarios',
}