import { themeInterface } from '../interface/themeInterface';

export const darkTheme: themeInterface = {
  HEADER_COLOR: '#e3170a',
  HEADER_TEXT_COLOR: 'white',
  PAGE_BACKGROUND_COLOR: '#e9ecef',
  CARD_BACKGROUND_COLOR: 'white',
  CLEAN_BUTTON_COLOR: '#023e8a',
  EDIT_BUTTON_COLOR: '#f6aa1c',
  PAY_BUTTON_COLOR: '#38b000',
  HOME_BUTTON_COLOR: '#595758',
  BACK_BUTTON_COLOR: '#457b9d',
  CARD_TEXT_BACKGROUND_COLOR: '#001d3d',
  CARD_TEXT_BACKGROUND_COLOR_PRODUCT: '#4d194d',
  CARD_BORDER_COLOR_PRODUCT: '#9f86c0',
  SPLASH_SCREEN_BACKGROUND_COLOR: '#c9184a',
  NUMBER_INDICATOR_BACKGROUND: '#d90429',
  TEXT_INDICATOR_COLOR: 'white',
  NUMBER_INDICATOR_SIZE: 45,
  MODAL_BACKGROUND_COLOR: 'white',
  COLOR_CLOSE_BUTTON: '#8d99ae',
  MODAL_TEXT_COLOR: 'black',
  CONFIRM_BUTTON_COLOR: '#4CAF50',
  CONFIRM_BUTTON_TEXT_COLOR: 'white',
  CANCEL_BUTTON_COLOR: '#f44336',
  CANCEL_BUTTON_TEXT_COLOR: 'white',
  NUMBER_EDIT_SHOPPING_CART_BACKGROUND_COLOR: '#dee2e6',
  NUMBER_EDIT_SHOPPING_CART_TEXT_COLOR: '#495057',
  NUMBER_EDIT_SHOPPING_CART_BORDER_COLOR: '#ced4da',
  FORM_COLOR: 'white',
  SECTION_BORDER_COLOR: '#c7ccdb',
  CARD_SELECTED_BORDER_COLOR: '#f6aa1c',
  LABEL_FORM_COLOR: '#495057',
  COLOR_FORM_ICON: '#495057',
  ERROR_COLOR: '#f44336',
  INPUT_BORDER_COLOR: '#B3E5FC',
  SELECTED_DATE_COLOR: '#0288D1',
  DIVIDER_COLOR: '#ced4da',
  EDIT_PRODUCT_BUTTON_COLOR: '#c9184a',
  SELECTED_EDIT_PRODUCT_BUTTON_COLOR: '#660708',
  // Input colors - Paleta Cielo de Verano
  INPUT_BACKGROUND_COLOR: '#F1F9FF',
  INPUT_BACKGROUND_COLOR_FOCUSED: '#E1F5FE',
  INPUT_BACKGROUND_COLOR_ERROR: '#FFF5F0',
  INPUT_ICON_BACKGROUND_COLOR: '#E1F5FE',
  INPUT_ICON_BACKGROUND_COLOR_FOCUSED: '#B3E5FC',
  INPUT_ICON_COLOR: '#03A9F4',
  INPUT_ICON_COLOR_FOCUSED: '#0288D1',
  INPUT_BORDER_COLOR_FOCUSED: '#0288D1',
  INPUT_PLACEHOLDER_COLOR: '#90A4AE',
  INPUT_SHADOW_COLOR: '#03A9F4',
  // Order status colors - Vibrant ice cream palette
  ORDER_STATUS_PENDING_PRIMARY: '#FF6B35', // Vibrant orange - like orange sherbet
  ORDER_STATUS_PENDING_SECONDARY: '#FFB700', // Golden amber
  ORDER_STATUS_IN_PROGRESS_PRIMARY: '#00B4D8', // Bright cyan - like blue raspberry
  ORDER_STATUS_IN_PROGRESS_SECONDARY: '#90E0EF', // Light cyan
  ORDER_STATUS_COMPLETED_PRIMARY: '#06D6A0', // Vibrant mint green
  ORDER_STATUS_COMPLETED_SECONDARY: '#52B788', // Fresh green
  ORDER_STATUS_CANCELLED_PRIMARY: '#EF476F', // Vibrant pink-red - like strawberry
  ORDER_STATUS_CANCELLED_SECONDARY: '#FF6D8F', // Light pink
  // Payment method colors
  PAYMENT_CASH_PRIMARY: '#06D6A0', // Mint green
  PAYMENT_CASH_SECONDARY: '#90F0DC', // Light mint
  PAYMENT_CARD_PRIMARY: '#7209B7', // Deep purple - like grape
  PAYMENT_CARD_SECONDARY: '#B185DB', // Light purple
  PAYMENT_MIXED_PRIMARY: '#FF8500', // Vibrant orange
  PAYMENT_MIXED_SECONDARY: '#FFB347', // Peach
  // Order card colors
  ORDER_CARD_GRADIENT_START: '#FFFFFF',
  ORDER_CARD_GRADIENT_END: '#F8F9FA',
  ORDER_CARD_SHADOW: 'rgba(0, 0, 0, 0.15)',
  ORDER_CARD_BORDER: '#E9ECEF',
  ORDER_BADGE_BACKGROUND: 'rgba(255, 255, 255, 0.95)',
  ORDER_BADGE_TEXT: '#FFFFFF',
  ORDER_ACCENT_COLOR: '#FF006E', // Hot pink - like raspberry sorbet
  ORDER_EMPTY_STATE_PRIMARY: '#FFD6FF', // Pastel pink
  ORDER_EMPTY_STATE_SECONDARY: '#E7C6FF', // Pastel purple
};
